name: vividsavitri
favicon: null
layout_spectrum: 0.9228533778805286
typography_spectrum: 0.10686432663351297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8910167035646737
  lightness: 0.8760499064810574
  saturation: 0.20300603937357664
  rhythmicContrast: 0.38384405011311173
purpose: []
